version: "3.8"
services:
  backend:
    image: backend:latest
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "wedd"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "a785410a"
    restart: always
  frontend:
    mem_limit: 700M
    image: front:latest
    container_name: frontend
    ports:
      - "80:3000"
    restart: always
  postgres:
    image: postgres:13.3
    hostname: postgres
    environment:
      POSTGRES_DB: "wedd"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "a785410a"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "3050:5432"
    restart: always