version: "3.8"
services:
  backend:
    image: backend:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "postgres:5432"
    restart: always
  frontend:
    image: frontend:latest
    ports:
      - "80:3000"
    restart: always
  postgres:
    image: postgres:13.3
    hostname: postgres
    environment:
      POSTGRES_DB: "wedd"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "a785410a"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "3050:5432"
    restart: always